language: node_js
node_js:
  - "8"
cache: yarn
sudo: required
services:
  - docker

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1

script:
  - $HOME/.yarn/bin/yarn install
  - $HOME/.yarn/bin/yarn build

deploy:
  - provider: script
    script: openssl aes-256-cbc -K $encrypted_4a63613bde44_key -iv $encrypted_4a63613bde44_iv -in ./k8s/travis-ci.credentials.json.enc -out ./k8s/travis-ci.credentials.json -d && docker login --username tourneytravisci --password $DOCKER_PASSWORD && bin/build-image.sh && bin/push-image.sh && bin/deploy.sh
    on:
      branch: master