language: node_js
node_js:
  - "8"

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1

script:
  - $HOME/.yarn/bin/yarn install
  - $HOME/.yarn/bin/yarn build
