apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tourney-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tourney-ui
    spec:
      containers:
      - name: tourney-ui
        image: andrewbackes/tourney-ui:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 2