apiVersion: v1
kind: Service
metadata:
  name: tourney-ui
  labels:
    app: tourney-ui
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    app: tourney-ui